import KalamehFont from "@/constans/localFont"
import '@/styles/globals.css'
import { Toaster } from "react-hot-toast"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <div>
      {children}
    </div>
  )
}
